import { Analytics } from '@vercel/analytics/next';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Analytics scriptSrc="https://analytics-script-git-tobiaslins-aly-1178-add-route-suppo-86a2b7.vercel.sh/v1/script.debug.js" />
        {children}
      </body>
    </html>
  );
}
