name: Publish
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install
        uses: ./.github/composite-actions/install
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci
      - name: Build
        run: pnpm -F @vercel/analytics build
      - run: pnpm -F @vercel/analytics publish --tag beta --no-git-checks
        if: github.event.release.prerelease == true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
      - run: pnpm -F@vercel/analytics publish --no-git-checks
        if: github.event.release.prerelease == false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
